### ISSUE TITLE
Switching desktops and moving windows between desktops is broken in 22H2

### ISSUE THREAD

**Issue by tgienger** [FancyWM/fancywm#197]
**Describe the bug**
"Your version of Windows is not supported"

what's broken:
switching desktops and moving windows between desktops

**Screenshots**
![image](https://github.com/FancyWM/fancywm/assets/4080971/89107d30-67c9-409e-97d1-93775fe5c38b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OS Build: 22H2
 - FancyWM Version: v2.11.2.0

**Comment by tgienger** [comment]
There's an update to VirtualDesktop, I believe FancyWM is using it. Can run it on it's own using whkb and it works. It's not ideal obviously I would rather it all be within Fancy. 

There also seem to be other issues like the fancywm window layouts performing strangely when switching between desktops. Nothing game breaking, just annoying. Like they have to refresh the layout every time the desktop is switched and it's slightly delayed/slow. It could be because fancy isn't managing the desktop switching or something else needs updated as well.

**Comment by tonylambert** [comment]
Is this what you are referring to with VirtualDesktop? https://github.com/Grabacr07/VirtualDesktop

**Comment by tgienger** [comment]
I used https://github.com/MScholtes/PSVirtualDesktop

Based on the same thing.

Then I used https://github.com/LGUG2Z/whkd to set some shortcuts instead of dealing with AHK

Here is my whkb file:

`
.shell pwsh

# switch desktop
alt + 1                 : Switch-Desktop -Desktop 0
alt + 2                 : Switch-Desktop -Desktop 1
alt + 3                 : Switch-Desktop -Desktop 2
alt + 4                 : Switch-Desktop -Desktop 3
alt + 5                 : Switch-Desktop -Desktop 4
alt + 6                 : Switch-Desktop -Desktop 5
alt + 7                 : Switch-Desktop -Desktop 6
alt + 8                 : Switch-Desktop -Desktop 7
alt + 9                 : Switch-Desktop -Desktop 8

# move windows to desktop
alt + shift + 1         : Move-ActiveWindow -Desktop 0
alt + shift + 2         : Move-ActiveWindow -Desktop 1
alt + shift + 3         : Move-ActiveWindow -Desktop 2
alt + shift + 4         : Move-ActiveWindow -Desktop 3
alt + shift + 5         : Move-ActiveWindow -Desktop 4
alt + shift + 6         : Move-ActiveWindow -Desktop 5
alt + shift + 7         : Move-ActiveWindow -Desktop 6
alt + shift + 8         : Move-ActiveWindow -Desktop 7
alt + shift + 9         : Move-ActiveWindow -Desktop 8

# move windows to desktop and switch
ctrl + shift + 1          : Move-ActiveWindow -Desktop 0 | Switch-Desktop -Desktop 0
ctrl + shift + 2          : Move-ActiveWindow -Desktop 1 | Switch-Desktop -Desktop 1
ctrl + shift + 3          : Move-ActiveWindow -Desktop 2 | Switch-Desktop -Desktop 2
ctrl + shift + 4          : Move-ActiveWindow -Desktop 3 | Switch-Desktop -Desktop 3
ctrl + shift + 5          : Move-ActiveWindow -Desktop 4 | Switch-Desktop -Desktop 4
ctrl + shift + 6          : Move-ActiveWindow -Desktop 5 | Switch-Desktop -Desktop 5
ctrl + shift + 7          : Move-ActiveWindow -Desktop 6 | Switch-Desktop -Desktop 6
ctrl + shift + 8          : Move-ActiveWindow -Desktop 7 | Switch-Desktop -Desktop 7
ctrl + shift + 9          : Move-ActiveWindow -Desktop 8 | Switch-Desktop -Desktop 8
`

**Comment by Md97SalahUddin** [comment]
am switching back to win10,i've tried many scripts that run natively with windows virtual desktops,but their not as smooth as running fancyWM,if any fix comes or theres a fork of this project made,please mention it here,it'd be really helpful.

**Comment by whaaaley** [comment]
Same here. When switching all my stacks get unstacked. It's really annoying.

**Comment by nikland** [comment]
@veselink1 buddy, you're gonna fix it? :(

**Comment by whaaaley** [comment]
@nikland Let's not badger our holy father, creator of all titles. I'm sure a fix is in the pipeline. A lot of these issues come out of no where and require a period of time to get familiar with what changed in Windows in order to make the fix.

**Comment by veselink1** [comment]
Should be fixed in https://github.com/FancyWM/fancywm/releases/tag/v2.11.3-rc.

**Comment by tgienger** [comment]
I'm no longer receiving any errors, but it still does not move to desktops

**Comment by tgienger** [comment]
Confirmed working now, thanks :)

**Comment by dallas145** [comment]
Thanks for update, will this update publish to Microsoft Store?

**Comment by whaaaley** [comment]
I stopped using FancyWM for a bit because of performance and random issues with Win11. I tried FancyZones + Groupy. Which was good and bad. Good, because I could rearrange Windows like Chrome tabs. Bad because I couldn't resize my tiles.

I came back to FancyWM to see if my issues were fixed, however, this bug is back, even in the latest RC.
Windows 11 Version 10.0.22631 Build 22631
