### ISSUE TITLE
Closing a virtual desktop that changes the number of other desktops crashes FancyWM

### ISSUE THREAD

**Issue by HarumiAme** [FancyWM/fancywm#54]
**Describe the bug**
If you have any number of desktops and close one that makes the other ones rearrange, FancyWM crashes with error "System.Runtime.InteropServices.COMException: Desktop does not exist!"

**To Reproduce**
1. Create 2 (or more) virtual desktops.
2. Close any of them except for the last.
4. FancyWM crashes.

**Expected behavior**
FancyWM shouldn't crash.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 21H2 64-bits

**Additional context**
If the desktop you close causes the desktop you're in to change number, the crash happens instantly. If your current desktop keeps the same number, the crash happens when you switch to one that was rearranged.

**Comment by veselink1** [comment]
Fixed in v2.6.1, thanks!

**Comment by HarumiAme** [comment]
The instant crash has been fixed, and switching desktops with the mouse works, but now FancyWM crashes when you change desktops with the keybinding. 

**To Reproduce**
1. Open 2 desktops (or more)
2. Close a desktop that makes the others rearrange
3. Switch to a rearranged one with the keybinding (Win + shift + number)
4. Same crash happens

Additionally, when you close a desktop, the popup that appears in the bottom shows the incorrect number of desktop. For example, if you open 3 desktops and close the 2nd, the third one shows "Desktop 1" when switching to it manually. 
Should I create a new issue with this info?

This is the log when it crashes
```
System.Runtime.InteropServices.COMException (0x80004005): Desktop does not exist!
   at WinMan.Windows.Win32VirtualDesktopService22000.GetComDesktop(Object desktopObj)
   at WinMan.Windows.Win32VirtualDesktopService22000.SwitchToDesktop(IntPtr hMon, Object desktop)
   at WinMan.Windows.FaultTolerantWin32VirtualDesktopService.<>c__DisplayClass16_0.<SwitchToDesktop>b__0()
   at WinMan.Windows.FaultTolerantWin32VirtualDesktopService.ExecuteWithRetry(Action action)
   at WinMan.Windows.FaultTolerantWin32VirtualDesktopService.SwitchToDesktop(IntPtr hMon, Object desktop)
   at WinMan.Windows.Win32VirtualDesktop.SwitchTo()
   at FancyWM.MainWindow.OnDesktopHotkeyPressed(Int32 desktopIndex)
   at FancyWM.MainWindow.ExecuteAction(BindableAction action, String& friendlyActionName)
   at FancyWM.MainWindow.OnCommandKey(IReadOnlySet`1 keys)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at FancyWM.Startup.Main(String[] args)
```

**Comment by GTonehour** [comment]
FancyWM still crashes on the "Switch to desktop" keyboard shortcut after a virtual desktop was closed. I think this issue should be reopened.
